# Generated by Django 4.2.6 on 2023-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-number']},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-number'], name='core_answer_number_0fc52a_idx'),
        ),
    ]
