# Generated by Django 4.2.6 on 2023-10-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullQtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='core_answer_number_0fc52a_idx',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test'),
        ),
        migrations.AddField(
            model_name='fullqtn',
            name='ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer'),
        ),
        migrations.AddField(
            model_name='fullqtn',
            name='qtn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
        migrations.AddField(
            model_name='fullqtn',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test'),
        ),
    ]
