# Generated by Django 4.2.6 on 2023-10-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fullqtn_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullQtn',
            new_name='Memorize',
        ),
        migrations.AddField(
            model_name='question',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
