# Generated by Django 4.2.6 on 2023-11-17 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 12, 51, 8, 572279, tzinfo=datetime.timezone.utc)),
        ),
    ]
