# Generated by Django 4.2.6 on 2023-11-21 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_post_date_posted_dms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dms',
            name='registered_user',
        ),
        migrations.AlterField(
            model_name='dms',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 8, 24, 23, 260870, tzinfo=datetime.timezone.utc)),
        ),
    ]
