# Generated by Django 4.2.6 on 2023-11-21 08:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_remove_dms_registered_user_alter_dms_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DMS',
            new_name='DM',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 8, 24, 57, 742025, tzinfo=datetime.timezone.utc)),
        ),
    ]
