# Generated by Django 4.2.6 on 2023-11-23 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_dms_dm_alter_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='starred',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 15, 57, 15, 788483, tzinfo=datetime.timezone.utc)),
        ),
    ]
