# Generated by Django 4.2.6 on 2023-12-01 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_quote_alter_post_date_posted_delete_dm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='grad_vids')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 23, 42, 75381, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 23, 42, 90956, tzinfo=datetime.timezone.utc)),
        ),
    ]
