# Generated by Django 4.2.6 on 2023-12-01 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_video_alter_post_date_posted_alter_quote_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default='vid', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 29, 25, 951679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 29, 25, 952680, tzinfo=datetime.timezone.utc)),
        ),
    ]
