# Generated by Django 4.2.6 on 2023-12-01 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_video_caption_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 47, 10, 759249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 47, 10, 755258, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 7, 47, 10, 756251, tzinfo=datetime.timezone.utc)),
        ),
    ]
