# Generated by Django 4.2.6 on 2023-12-16 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_video_date_posted_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 7, 31, 46, 918048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 7, 31, 46, 919048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 7, 31, 46, 922047, tzinfo=datetime.timezone.utc)),
        ),
    ]
